# Generated by Django 4.0.6 on 2022-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pis', models.CharField(max_length=12, verbose_name='PIS')),
                ('matricula', models.CharField(max_length=5, verbose_name='Matrícula')),
                ('entrada', models.CharField(choices=[('7', '7:00'), ('8', '8:00')], max_length=1)),
                ('almoco', models.CharField(choices=[('11', '11:00'), ('12', '12:00'), ('13', '13:00')], max_length=2, verbose_name='Almoço')),
            ],
            options={
                'verbose_name': 'Funcionário',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('dados', models.FileField(upload_to='media/')),
            ],
        ),
    ]
