# Generated by Django 4.0.6 on 2022-08-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário'},
        ),
    ]
