# Generated by Django 4.0.6 on 2022-08-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_funcionario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
