# Generated by Django 4.0.6 on 2022-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_funcionario_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('dados', models.BinaryField()),
            ],
        ),
    ]
