# Generated by Django 4.0.6 on 2022-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0006_alter_ponto_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='almoco',
            field=models.CharField(choices=[('11', '11:00'), ('12', '12:00'), ('13', '13:00')], default='11', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='entrada',
            field=models.CharField(choices=[('7', '7:00'), ('8', '8:00')], default='8', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=5, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(max_length=12, verbose_name='PIS'),
        ),
    ]
